// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSywb4hV7OgBOQk1gJNBoGmCMwxZcJSHw',
    appId: '1:871496456240:web:e3bb73eaa83375a08eb5f5',
    messagingSenderId: '871496456240',
    projectId: 'auth-ebcc5',
    authDomain: 'auth-ebcc5.firebaseapp.com',
    storageBucket: 'auth-ebcc5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaFuJq0kfjkLs1CYJoxQRL4XSi3IebPJs',
    appId: '1:871496456240:android:bd4d83d0df44ba9c8eb5f5',
    messagingSenderId: '871496456240',
    projectId: 'auth-ebcc5',
    storageBucket: 'auth-ebcc5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvdCjeyUSsiXM6cbu43cf2TcoltGAvw54',
    appId: '1:871496456240:ios:bf0e36ee1f961c038eb5f5',
    messagingSenderId: '871496456240',
    projectId: 'auth-ebcc5',
    storageBucket: 'auth-ebcc5.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvdCjeyUSsiXM6cbu43cf2TcoltGAvw54',
    appId: '1:871496456240:ios:bf0e36ee1f961c038eb5f5',
    messagingSenderId: '871496456240',
    projectId: 'auth-ebcc5',
    storageBucket: 'auth-ebcc5.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSywb4hV7OgBOQk1gJNBoGmCMwxZcJSHw',
    appId: '1:871496456240:web:baee3107ea4cc3918eb5f5',
    messagingSenderId: '871496456240',
    projectId: 'auth-ebcc5',
    authDomain: 'auth-ebcc5.firebaseapp.com',
    storageBucket: 'auth-ebcc5.firebasestorage.app',
  );
}
